audit_header: false
title: "Best Real Estate Training"
description: Angelia Black, a top Real Estate Agent in Cornelius, shares her own internal real estate agent training for free. Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Upcoming Events
    url: https://www.eventbrite.com/o/sellstate-premier-19728565982
  - title: Who We Recommend
    url: /recommend/
client:
  name: Angelia Black
  title:
  license_number:
  about_markdown: |
    In real estate since 2000, Angelia Black has been leading the Charlotte area real estate market with innovative approaches to systems, marketing, and coaching. She's coached hundreds of agents nationwide and has closed millions of dollars in volume over the last several years. Angelia has created a productive environment that allows agents to grow their business fast and in a sustainable manner.

    Angelia launched the Sellstate Premier brand in North Carolina in 2019 and is CEO of the company. She also a mom of 2 great kids, enjoys reading and traveling, Fun fact: she's also a twin.
  market: Cornelius
  brand: Sellstate Premier
  brokerage:
  address: 16405 Northcross Drive Suite G1 Huntersville, NC 28078
  phone: 980-477-1838
  phone_type:
  phone2:
  phone2_type:
  email: careers@sellstatepremier.com
  url:

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Sellstate Premier can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/sellstatepremier/?modal=admin_todo_tour
  linkedin_url: https://www.linkedin.com/in/angelia-black-77685626/
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UCxtRt9sNDce-PCPkFClvN8g?view_as=subscriber
  twitter_url: https://twitter.com/Sellstepremier
  instagram_url: https://www.instagram.com/sellstatepremier/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://podcasts.apple.com/us/podcast/cornelius-real-estate-podcast-with-angelia-black/id1466860979

podcast:
  title: 'Cornelius Real Estate Podcast with Angelia Black'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Cornelius Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Sellstate Premier - your professional Cornelius Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Cornelius, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Angelia Black'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Sellstate Premier
  hero_subtitle: Area’s Fastest Growing Real Estate Company
  hero_background_hex: '#999'
  hero_image_path: /img/background2.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#004d9a'
  theme_color: '#818285'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#ffffff'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
